import type { Metadata } from 'next';
import { MkNavbar } from '@/components/layout/MkNavbar';
import { MkFooter } from '@/components/layout/MkFooter';

export const metadata: Metadata = {
  title: 'Terms & Conditions | MK Gold',
  description: 'MK Gold terms and conditions — service scope, valuation terms, payment, and governing law.',
  alternates: { canonical: 'https://mkgold.in/terms' },
  robots: { index: true, follow: true },
};

const LAST_UPDATED = '1 January 2025';

export default function TermsPage() {
  return (
    <>
      <MkNavbar />
      <main style={{ paddingTop: 'var(--chrome-h)' }}>

        {/* Hero */}
        <section className="mk-bg-dark section--sm">
          <div className="mk-container" style={{ maxWidth: '800px' }}>
            <p className="mk-section-overline">Legal</p>
            <h1 style={{ fontFamily: 'Tanker, serif', fontSize: 'var(--t-h1)', color: 'white', lineHeight: 1.1, margin: '0.5rem 0 1rem' }}>
              Terms &amp; Conditions
            </h1>
            <p style={{ fontFamily: 'Poppins, sans-serif', fontSize: 'var(--t-sm)', color: 'rgba(255,255,255,0.55)', margin: 0 }}>
              Last updated: {LAST_UPDATED}
            </p>
          </div>
        </section>

        {/* Content */}
        <section className="mk-bg-light section">
          <div className="mk-container" style={{ maxWidth: '800px' }}>
            <div style={{ fontFamily: 'Poppins, sans-serif', fontSize: 'var(--t-base)', color: 'var(--ink-mid)', lineHeight: 1.8 }}>

              <Section title="1. Acceptance of Terms">
                By using the MK Gold website (mkgold.in) or visiting any MK Gold branch, you agree to be bound by these Terms and Conditions. If you do not agree, please do not use our website or services. These Terms apply in addition to any applicable laws and regulations of India.
              </Section>

              <Section title="2. About MK Gold">
                MK Gold is a gold buying company registered and operating in Karnataka, India. We purchase gold jewellery, gold coins, gold bars, and broken gold from individuals. We do not provide loans, financial advice, or investment services.
              </Section>

              <Section title="3. Service Scope">
                <p>Our services include:</p>
                <ul style={{ paddingLeft: '1.5rem', marginTop: '0.5rem' }}>
                  <li style={{ marginBottom: '0.5rem' }}>Purchase of physical gold from individuals at MCX-linked rates</li>
                  <li style={{ marginBottom: '0.5rem' }}>XRF purity testing (free of charge, non-destructive)</li>
                  <li style={{ marginBottom: '0.5rem' }}>Assistance with pledged gold release from banks and NBFCs</li>
                  <li style={{ marginBottom: '0.5rem' }}>Branch appointment booking and valuation enquiries</li>
                </ul>
                <p style={{ marginTop: '1rem' }}>Services are available at all 16 MK Gold branches in Bangalore, Mysore, Mangalore, and Davangere.</p>
              </Section>

              <Section title="4. Gold Rate and Valuation">
                <p>The gold rates displayed on our website are indicative only. They are based on live MCX (Multi Commodity Exchange) data refreshed every 5 minutes and are subject to change without notice.</p>
                <p style={{ marginTop: '1rem' }}>The final offer for your gold is determined at the branch after:</p>
                <ol style={{ paddingLeft: '1.5rem', marginTop: '0.5rem' }}>
                  <li style={{ marginBottom: '0.5rem' }}>Physical weighing on certified precision scales</li>
                  <li style={{ marginBottom: '0.5rem' }}>XRF purity testing using a Bruker spectrometer</li>
                  <li style={{ marginBottom: '0.5rem' }}>Application of the prevailing MCX rate at the time of the transaction</li>
                </ol>
                <p style={{ marginTop: '1rem' }}>The calculator on our website provides an estimate only. MK Gold is not bound by any estimate generated by the online calculator. No purchase agreement is formed until a formal written offer is made and accepted at a branch.</p>
              </Section>

              <Section title="5. Customer Obligations">
                <p>To complete a gold sale transaction, you must:</p>
                <ul style={{ paddingLeft: '1.5rem', marginTop: '0.5rem' }}>
                  <li style={{ marginBottom: '0.5rem' }}>Be 18 years of age or older</li>
                  <li style={{ marginBottom: '0.5rem' }}>Be the lawful owner of the gold being sold, or be duly authorised to sell it</li>
                  <li style={{ marginBottom: '0.5rem' }}>Present a valid government-issued photo ID (Aadhaar, PAN, Passport, Voter ID, or Driving Licence)</li>
                  <li style={{ marginBottom: '0.5rem' }}>Provide accurate and truthful information about the gold</li>
                </ul>
                <p style={{ marginTop: '1rem' }}>MK Gold reserves the right to decline any transaction where we have reasonable grounds to suspect fraud, misrepresentation, or unlawful origin of gold.</p>
              </Section>

              <Section title="6. Payment">
                Payment for purchased gold is made immediately upon acceptance of the offer at the branch, by cash (up to permissible limits under applicable law), NEFT, RTGS, or UPI. MK Gold does not make payment in advance of the branch transaction.
              </Section>

              <Section title="7. Pledged Gold Release">
                <p>For pledged gold release services, MK Gold acts as an intermediary to pay the outstanding loan amount directly to your bank or NBFC, with the balance remitted to you. This service is subject to:</p>
                <ul style={{ paddingLeft: '1.5rem', marginTop: '0.5rem' }}>
                  <li style={{ marginBottom: '0.5rem' }}>The lender&apos;s acceptance of the repayment</li>
                  <li style={{ marginBottom: '0.5rem' }}>The gold being available for release and valued above the outstanding loan</li>
                  <li style={{ marginBottom: '0.5rem' }}>Your identity and ownership being verifiable</li>
                </ul>
                <p style={{ marginTop: '1rem' }}>MK Gold is not responsible for delays caused by the lender&apos;s internal processes.</p>
              </Section>

              <Section title="8. Website Use">
                <p>You agree to use the MK Gold website for lawful purposes only. You must not:</p>
                <ul style={{ paddingLeft: '1.5rem', marginTop: '0.5rem' }}>
                  <li style={{ marginBottom: '0.5rem' }}>Attempt to disrupt, damage, or gain unauthorised access to our systems</li>
                  <li style={{ marginBottom: '0.5rem' }}>Submit false or misleading information through any form</li>
                  <li style={{ marginBottom: '0.5rem' }}>Use automated tools to scrape, crawl, or extract data from our website without written permission</li>
                </ul>
              </Section>

              <Section title="9. Intellectual Property">
                All content on this website — including the MK Gold logo, wordmark, brand colours, text, graphics, and page designs — is the property of MK Gold. No part may be copied, reproduced, or distributed without prior written permission.
              </Section>

              <Section title="10. Disclaimer of Warranties">
                The MK Gold website and its content are provided &ldquo;as is&rdquo; without warranties of any kind, express or implied. We do not warrant that the website will be uninterrupted, error-free, or free of viruses. Gold rate information is indicative only and not financial advice.
              </Section>

              <Section title="11. Limitation of Liability">
                To the maximum extent permitted by applicable law, MK Gold shall not be liable for any indirect, incidental, or consequential damages arising from your use of our website or services. Our total liability to you in connection with any transaction shall not exceed the value of that transaction.
              </Section>

              <Section title="12. Governing Law and Jurisdiction">
                These Terms are governed by the laws of India. Any disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in Bangalore, Karnataka.
              </Section>

              <Section title="13. Grievance Redressal">
                <p>If you have a complaint about our services, please contact our grievance officer:</p>
                <p style={{ marginTop: '0.75rem' }}>
                  <strong>Grievance Officer — MK Gold</strong><br />
                  Email: <a href="mailto:grievance@mkgold.in" style={{ color: 'var(--plum)', fontWeight: 500 }}>grievance@mkgold.in</a><br />
                  Phone: <a href="tel:+917019500600" style={{ color: 'var(--plum)', fontWeight: 500 }}>+91 70195 00600</a><br />
                  We will acknowledge your complaint within 48 hours and resolve it within 30 days.
                </p>
              </Section>

              <Section title="14. Changes to Terms">
                MK Gold reserves the right to update these Terms at any time. The &ldquo;Last updated&rdquo; date at the top indicates the most recent revision. Continued use of our website or services after any change constitutes acceptance of the revised Terms.
              </Section>

            </div>
          </div>
        </section>

      </main>
      <MkFooter />
    </>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: '2.5rem' }}>
      <h2 style={{ fontFamily: 'Tanker, serif', fontSize: 'var(--t-h3)', color: 'var(--ink)', marginBottom: '0.875rem', lineHeight: 1.2 }}>
        {title}
      </h2>
      <div style={{ fontFamily: 'Poppins, sans-serif', fontSize: 'var(--t-base)', color: 'var(--ink-mid)', lineHeight: 1.8 }}>
        {children}
      </div>
    </div>
  );
}
